Add check for code format in CI
Ericsson/ered pull request #4
Opened 2022-06-09 12:22 UTC by bjosv

Adds a check in CI to make sure that new code is formatted according to the emacs-mode standard.
The`erlang-formatter` is used and can be run via `rebar3 fmt`.

2022-06-09 12:25 UTC, bjosv commented on src/ered_parser.erl
> +          <<"*?">>             -> aggregate_stream(parse_array([]));
erlang-formatter runs something like
`emacs --batch --directory _build/erlang-formatter-master/priv --load _build/erlang-formatter-master/priv/fmt.el ./src/ered_parser.erl`,
where fmt.el is provided by the erlang-formatter. An own quite updated erlang.el is also included in erlang-formatter.

Having an own emacs-function in my Emacs config:
```
(defun my-erlang-format ()
  (interactive)
  (erlang-mode)
  (erlang-indent-current-buffer))
```
..and running in on a buffer seems to give the same results as in this commit. Just running `erlang-indent-current-buffer` in emacs results in the expected indentation..
I don't understand why..
I get the same issues with https://github.com/tduffield/erl-indent

2022-06-09 15:25 UTC, zuiderkwast requested changes
Nice. Not nice that it fails on the binary patterns though.

2022-06-09 15:25 UTC, zuiderkwast commented on test/ered_client_tests.erl
> +                                                % expect 5 ping
```suggestion
                       %% expect 5 ping
```

2022-06-09 15:25 UTC, zuiderkwast commented on test/ered_client_tests.erl
> +                                                % should be nothing more since only 5 pending
```suggestion
                      %% should be nothing more since only 5 pending
```

2022-06-09 15:25 UTC, zuiderkwast commented on test/ered_client_tests.erl
> +                                                % should be nothing more since only 5 pending
```suggestion
                       %% should be nothing more since only 5 pending
```

2022-06-09 15:25 UTC, zuiderkwast commented on test/ered_client_tests.erl
> +                                                % expect 5 ping
```suggestion
                       %% expect 5 ping
```

2022-06-09 15:25 UTC, zuiderkwast commented on test/ered_client_tests.erl
> +                                                % should be nothing more since only 5 pending
```suggestion
                       %% should be nothing more since only 5 pending
```

2022-06-09 15:25 UTC, zuiderkwast commented on src/ered_parser.erl
> +          <<"*?">>             -> aggregate_stream(parse_array([]));
I don't understand either. We need to fix this before merge.

2022-06-10 14:04 UTC, zuiderkwast commented on src/ered_parser.erl
> +          <<"*?">>             -> aggregate_stream(parse_array([]));
I think that somehow emacs treats `$"` is an escaped character. As a workaround, we could change `"$"` to `$$` here. Then it (probably) works regardless of emacs and erlang-formatter versions. WDYT?

2022-06-13 07:19 UTC, bjosv commented on src/ered_parser.erl
> +          <<"*?">>             -> aggregate_stream(parse_array([]));
Yes, we can change this and change back when/if the formatter gets fixed.
Pushed the change.

2022-06-13 08:50 UTC, zuiderkwast approved these changes

2022-06-13 10:34 UTC, merged